Wyjątki dzielimy na wyjątki nieobsługiwane które trzeba obsłużyć i wyjątki obsługiwane które można, ale nie trzeba obsłużyć.
Wyjątk nieobsługiwane dziedziczą po klasie RuntimeException
Wyjątki rzucamy korzystając z instrukcji try-catch, jeśli rzucamy wyjątek kontrolowany musimy dodatkowo w sygnaturze metody/konstruktora zadeklarować wyjątek używając słowa throws
Do bloku try-catch możemy dodać dodatkowo blok finally, który wykona się zawsze, niezależnie, czy w bloku try wyjątek wystąpił, czy nie.